apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      variant: simple-landing-page

resources:
  - ../../base

patches:
  - path: ingress.yaml
